!function(e){var n={};function t(r){if(n[r])return n[r].exports;var o=n[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}t.m=e,t.c=n,t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{enumerable:!0,get:r})},t.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},t.t=function(e,n){if(1&n&&(e=t(e)),8&n)return e;if(4&n&&"object"==typeof e&&e&&e.__esModule)return e;var r=Object.create(null);if(t.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:e}),2&n&&"string"!=typeof e)for(var o in e)t.d(r,o,function(n){return e[n]}.bind(null,o));return r},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},t.p="",t(t.s="./AuthMain.ts")}({"./AuthAdapt.ts":
/*!**********************!*\
  !*** ./AuthAdapt.ts ***!
  \**********************/
/*! no static exports found */function(module,exports,__webpack_require__){"use strict";eval("\r\nObject.defineProperty(exports, \"__esModule\", { value: true });\r\nconst AuthDomElements_1 = __webpack_require__(/*! ./AuthDomElements */ \"./AuthDomElements.ts\");\r\nclass AuthAdapt {\r\n    constructor() {\r\n        this.width = document.body.clientWidth;\r\n        this.height = screen.height;\r\n    }\r\n    init() {\r\n        const authDomElements = new AuthDomElements_1.AuthDomElements();\r\n        window.addEventListener('load', () => {\r\n            this.width = document.body.clientWidth;\r\n            this.height = screen.height;\r\n            if (this.width < 576) {\r\n                this.addClass();\r\n            }\r\n            else if (this.width > 575) {\r\n                this.removeClass();\r\n            }\r\n        });\r\n        window.addEventListener('resize', () => {\r\n            this.width = document.body.clientWidth;\r\n            this.height = screen.height;\r\n            if (this.width < 576) {\r\n                this.addClass();\r\n            }\r\n            else if (this.width > 575) {\r\n                this.removeClass();\r\n            }\r\n        });\r\n        // Height of main container\r\n        authDomElements.mainContainer.style.minHeight = (this.height - 150).toString() + 'px';\r\n    }\r\n    /** Add a new classes for mobile mode */\r\n    addClass() {\r\n        // const authDomElements = new AuthDomElements();\r\n    }\r\n    /** Remove mobile mode classes */\r\n    removeClass() {\r\n        // const authDomElements = new AuthDomElements();\r\n    }\r\n}\r\nexports.AuthAdapt = AuthAdapt;\r\n\n\n//# sourceURL=webpack:///./AuthAdapt.ts?")},"./AuthDomElements.ts":
/*!****************************!*\
  !*** ./AuthDomElements.ts ***!
  \****************************/
/*! no static exports found */function(module,exports,__webpack_require__){"use strict";eval("\r\nObject.defineProperty(exports, \"__esModule\", { value: true });\r\nclass AuthDomElements {\r\n    constructor() {\r\n        this.mainContainer = document.querySelector('.main-container');\r\n        this.signInForm = document.querySelector('.signin-form');\r\n        this.signUpForm = document.querySelector('.signup-form');\r\n        this.signInLink = document.querySelector('.signin-link');\r\n        this.signUpLink = document.querySelector('.signup-link');\r\n        this.formWrp = document.querySelector('.form-wrp');\r\n        this.formHeader = document.querySelector('.form-header');\r\n        this.activeLink = document.querySelector('.active-link');\r\n    }\r\n}\r\nexports.AuthDomElements = AuthDomElements;\r\n\n\n//# sourceURL=webpack:///./AuthDomElements.ts?")},"./AuthFormChanger.ts":
/*!****************************!*\
  !*** ./AuthFormChanger.ts ***!
  \****************************/
/*! no static exports found */function(module,exports,__webpack_require__){"use strict";eval("\r\nObject.defineProperty(exports, \"__esModule\", { value: true });\r\nconst AuthDomElements_1 = __webpack_require__(/*! ./AuthDomElements */ \"./AuthDomElements.ts\");\r\nconst authDomElements = new AuthDomElements_1.AuthDomElements();\r\nclass AuthFormChanger {\r\n    init() {\r\n        document.addEventListener('DOMContentLoaded', () => {\r\n            authDomElements.signInLink.addEventListener('click', () => { this.showSignInForm(); });\r\n            authDomElements.signUpLink.addEventListener('click', () => { this.showSignUpForm(); });\r\n        });\r\n    }\r\n    showSignInForm() {\r\n        authDomElements.signUpForm.style.display = 'none';\r\n        authDomElements.signInForm.style.display = 'block';\r\n        authDomElements.formWrp.style.height = '650px';\r\n        authDomElements.formHeader.innerHTML = 'Вхід';\r\n        authDomElements.signInLink.classList.add('active-link');\r\n        authDomElements.signUpLink.classList.remove('active-link');\r\n    }\r\n    showSignUpForm() {\r\n        authDomElements.signInForm.style.display = 'none';\r\n        authDomElements.signUpForm.style.display = 'block';\r\n        authDomElements.formWrp.style.height = '800px';\r\n        authDomElements.formHeader.innerHTML = 'Реєстрація';\r\n        authDomElements.signUpLink.classList.add('active-link');\r\n        authDomElements.signInLink.classList.remove('active-link');\r\n    }\r\n}\r\nexports.AuthFormChanger = AuthFormChanger;\r\n\n\n//# sourceURL=webpack:///./AuthFormChanger.ts?")},"./AuthMain.ts":
/*!*********************!*\
  !*** ./AuthMain.ts ***!
  \*********************/
/*! no static exports found */function(module,exports,__webpack_require__){"use strict";eval('\r\nObject.defineProperty(exports, "__esModule", { value: true });\r\nconst AuthAdapt_1 = __webpack_require__(/*! ./AuthAdapt */ "./AuthAdapt.ts");\r\nconst AuthFormChanger_1 = __webpack_require__(/*! ./AuthFormChanger */ "./AuthFormChanger.ts");\r\nclass PhotosMain {\r\n    init() {\r\n        const authAdapt = new AuthAdapt_1.AuthAdapt();\r\n        const authFormChanger = new AuthFormChanger_1.AuthFormChanger();\r\n        authAdapt.init();\r\n        authFormChanger.init();\r\n    }\r\n}\r\nconst main = new PhotosMain();\r\nmain.init();\r\n\n\n//# sourceURL=webpack:///./AuthMain.ts?')}});